### PR TITLE
Add initial CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by andrewlock**

### CODE REVIEW

**Comment by kaylangan** [comment]
I'm a Program Manager for Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by vtbassmatt** [comment]
Hey @andrewlock, I'm on Kayla's team and she asked me to take a look here. The software on each of our images is listed [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#software). It looks like we don't offer 1.1.2 on the Ubuntu or Mac images, though we do on Windows. I can see about getting that version added...

Your bigger problem is that your tool installers are clobbering each other. The list of steps is processed sequentially. So for instance in the Linux job, you're asking for 1.0.4, then immediately switching to 1.1.4, then immediately switching to 2.1.401.

Instead, you probably want that in a matrix so it runs once for each .NET Core version:

```yaml
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      DotNet10:
        dotnet_version: '1.0.4'
      DotNet11:
        dotnet_version: '1.1.4'
      DotNet20:
        dotnet_version: '2.0.401'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: $( dotnet_version )
  - bash: ./build.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
```

And similar for the other platforms. (Once you get that going, we could also look at factoring your job out into a template so you don't have to duplicate the steps on each platform... but one thing at a time.)

**Comment by andrewlock** [comment]
Hi @vtbassmatt,
Thanks for the clarification. Looking at that list of software it seems like I shouldn't need to install any more .NET Core SDKs, there's already a tonne installed though there's a _lot_ of duplicates in [this link](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md).

And also, to be clear, I'm not trying to get a "matrix so it runs once for each .NET Core version". If you see the Windows build (that succeeded) its just a single build, it just runs the tests once on each target framework as part of that.

I'll try tweaking some things.

**Comment by andrewlock** [comment]
Also, I'm not sure "Your bigger problem is that your tool installers are clobbering each other" holds true given that the build passes on Windows 🙂

**Comment by andrewlock** [comment]
In fact, removing the installer steps completely fixes the mac build, and the Windows build still succeeds. Linux is still broken though 🤔

**Comment by andrewlock** [comment]
So in that build you linked to, if you scroll down (a long way) in the powershell task log, you'll see this:

```
2018-09-20T19:45:45.1279737Z Testing project D:/a/1/s/test/NetEscapades.Configuration.Yaml.Tests/NetEscapades.Configuration.Yaml.Tests.csproj
2018-09-20T19:45:45.8247248Z Test run for D:\a\1\s\test\NetEscapades.Configuration.Yaml.Tests\bin\Release\net452\NetEscapades.Configuration.Yaml.Tests.dll(.NETFramework,Version=v4.5.2)
2018-09-20T19:45:45.8837680Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-09-20T19:45:45.8838953Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-09-20T19:45:45.8839077Z 
2018-09-20T19:45:45.9484113Z Starting test execution, please wait...
2018-09-20T19:45:47.2068445Z 
2018-09-20T19:45:47.2073791Z Total tests: 24. Passed: 24. Failed: 0. Skipped: 0.
2018-09-20T19:45:47.2074225Z Test Run Successful.
2018-09-20T19:45:47.2075245Z Test execution time: 1.2101 Seconds
2018-09-20T19:45:47.2644640Z Test run for D:\a\1\s\test\NetEscapades.Configuration.Yaml.Tests\bin\Release\netcoreapp2.0\NetEscapades.Configuration.Yaml.Tests.dll(.NETCoreApp,Version=v2.0)
2018-09-20T19:45:47.3226811Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-09-20T19:45:47.3227333Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-09-20T19:45:47.3227546Z 
2018-09-20T19:45:47.3908942Z Starting test execution, please wait...
2018-09-20T19:45:50.0118444Z 
2018-09-20T19:45:50.0124611Z Total tests: 24. Passed: 24. Failed: 0. Skipped: 0.
2018-09-20T19:45:50.0124889Z Test Run Successful.
2018-09-20T19:45:50.0125702Z Test execution time: 2.5683 Seconds
2018-09-20T19:45:50.0736372Z Test run for D:\a\1\s\test\NetEscapades.Configuration.Yaml.Tests\bin\Release\netcoreapp1.1\NetEscapades.Configuration.Yaml.Tests.dll(.NETCoreApp,Version=v1.1)
2018-09-20T19:45:50.1336019Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-09-20T19:45:50.1336569Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-09-20T19:45:50.1336717Z 
2018-09-20T19:45:50.1947645Z Starting test execution, please wait...
2018-09-20T19:45:53.1239581Z 
2018-09-20T19:45:53.1245340Z Total tests: 24. Passed: 24. Failed: 0. Skipped: 0.
2018-09-20T19:45:53.1245646Z Test Run Successful.
2018-09-20T19:45:53.1249242Z Test execution time: 2.8773 Seconds
```

That shows it running the same project against .NETFramework,Version=v4.5.2, NETCoreApp,Version=v2.0, and NETCoreApp,Version=v1.1. 
Cake's basically just doing a `dotnet test` under the hood, and that's a multi- targeted project.

The weird thing is I don't know _why_ it needs 1.1.2 at the moment. According to the install list you posted previously, neither the Mac or Windows machines have 1.1.2 installed either, yet they are building fine in the latest iteration. 

So it's just linux. It's as though the other .net runtimes haven't been installed even though they should be according to the list of installed software. I'll add a task to run `dotnet --info` to see what's _actually_ on there at some point soon, because it's all a bit odd.

**Comment by andrewlock** [comment]
@vtbassmatt I just added a call to `dotnet --info` to [the test run](https://dev.azure.com/andrewlocknet/NetEscapades.Configuration/_build/results?buildId=17&view=logs). It confirms that the list of software installed is incorrect. Or that the .NET SDKs have been installed incorrectly. Only the 2.1.401 SDK (2.1.3 runtime) is available:

```
dotnet --info
2018-09-27T15:17:29.2357113Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/e8a76760-d87f-4530-9c87-66bf30815062.sh
2018-09-27T15:17:36.2690537Z .NET Core SDK (reflecting any global.json):
2018-09-27T15:17:36.2702134Z  Version:   2.1.401
2018-09-27T15:17:36.2716058Z  Commit:    91b1c13032
2018-09-27T15:17:36.2721591Z 
2018-09-27T15:17:36.2733082Z Runtime Environment:
2018-09-27T15:17:36.2745351Z  OS Name:     ubuntu
2018-09-27T15:17:36.2758376Z  OS Version:  16.04
2018-09-27T15:17:36.2770283Z  OS Platform: Linux
2018-09-27T15:17:36.6309387Z  RID:         ubuntu.16.04-x64
2018-09-27T15:17:36.6447295Z  Base Path:   /usr/share/dotnet/sdk/2.1.401/
2018-09-27T15:17:36.6464558Z 
2018-09-27T15:17:36.6478058Z Host (useful for support):
2018-09-27T15:17:36.6490366Z   Version: 2.1.3
2018-09-27T15:17:36.6505758Z   Commit:  124038c13e
2018-09-27T15:17:36.6512221Z 
2018-09-27T15:17:36.6525764Z .NET Core SDKs installed:
2018-09-27T15:17:36.6538805Z   2.1.401 [/usr/share/dotnet/sdk]
2018-09-27T15:17:36.6545580Z 
2018-09-27T15:17:36.6557977Z .NET Core runtimes installed:
2018-09-27T15:17:36.6571627Z   Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
2018-09-27T15:17:36.6584647Z   Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
2018-09-27T15:17:36.6597187Z   Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
2018-09-27T15:17:36.6602945Z 
2018-09-27T15:17:36.6617187Z To install additional .NET Core runtimes or SDKs:
2018-09-27T15:17:36.6631588Z   https://aka.ms/dotnet-download
```
They're meant to side-by-side installations, that's one of the selling points of .NET Core, but it looks like that's not the case 

**Edit:** Very strangely, I just [ran it again](https://dev.azure.com/andrewlocknet/NetEscapades.Configuration/_build/results?buildId=19&view=logs), and this time it shows all the installed .NET Core runtimes and SDKs! and lo and behold the build succeeds. 

This looks to me like a definite bug on the Azure pipelines side - the agent I got in the last run was _definitely_ different to the one before!

**Comment by vtbassmatt** [comment]
@dakale are you the right person to investigate this? It's strange that in consecutive runs, we'd see such divergent agent behavior.

**Comment by dakale** [comment]
It looks like there are some mismatches in image versions on the Ubuntu pools. Some machines have an older image, which dont have all the SDKs installed. Ill fix today

**Comment by andrewlock** [comment]
Great, that sounds like it explains it! thanks both 🙂

**Comment by andrewlock** [comment]
All looks to be sorted now I think, so merged this now. Thanks.

**Pull request merged**
