### PR TITLE
Add yaml stream config source

### PR DESCRIPTION
**Pull request by mihailpw**
Add YAML Stream config source like for JSON in .NET ([source.dot.net](https://source.dot.net/#Microsoft.Extensions.Configuration.Json/JsonConfigurationExtensions.cs,bf88a21de5a23e1a))

### CODE REVIEW

**Comment by mihailpw** [comment]
PTAL @andrewlock

**Comment by thedmi** [comment]
This looks like exactly what we need. And apparently there are other requests for such a feature as well (see #76).

@andrewlock  Any chance you could take a look so we can move this forward? I'd be willing to help if there is anything I can do.

**Review by andrewlock — APPROVED** [review]
Thanks for this @mihailpw, this looks great! I'll get a new release out that includes this update soon 👍

**Comment by andrewlock** [comment]
I was just thinking about this PR again, and I think there could be concerns with how ownership and how reloading works. 

The configuration APIs allow for loading the data multiple times, and also don't define exactly _when_ the data is loaded. With the current API, you pass in a `Stream` but we don't take ownership of the `Stream` so we don't close/dispose it etc. If the _caller_ (correctly) disposes the stream, we might try and subsequently read from it.

For example, if you pass in a stream, and "partially build" the configuration, you'll get an exception. For example, code like this will throw a `System.ArgumentException: Stream was not readable`:

```csharp
using var fileStream = File.OpenRead("appsettings.yml");
builder
    .AddYamlStream(fileStream)
    .Build();
```

And if the stream _isn't_ disposed, then on the second reading it will be empty. So whatever you do, you get the wrong results 🙁 

I'm thinking about reworking the `AddYamlStream` to _immediately_ read the stream. That way it can be disposed safely, and will only ever read once. I'll create a PR for this approach shortly

**Pull request merged**
